### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by jekader** [sysint64/e2dit#7]
Hey, I tried to build the project and it seems to miss some dependencies:

> $ make/linux_debug.sh
> MainSFML.cpp:9:23: fatal error: glm/glm.hpp: No such file or directory
> # include <glm/glm.hpp>
> 
> ```
>                   ^    compilation terminated.
> ```

I propose adding required dependencies to the README

**Comment by sysint64** [comment]
you must install the following libraries: soil; glew32; sfwml-2.1; ftgl; freetype2; glm; tinyxml; jpeg;
Added to readme, thanks;

**Comment by jekader** [comment]
Thanks! These were the build dependencies I had to install on Debian:

apt-get install g++ libglm-dev libglew-dev libsfml-dev libsoil-dev libftgl-dev libfreetype6-dev libjpeg-dev libtinyxml2-dev
